formats:
  - oas3
  - oas2
  - json-schema
extends:
  - 'spectral:oas'
rules:
  info-matches-stoplight:
    description: This is an example rule
    message: Info must contain Stoplight
    given: $.info
    recommended: true
    type: style
    then:
      field: title
      function: pattern
      functionOptions:
        match: Stoplight
  api-host: error
  api-servers: 'off'
  definition-description: info
