openapi: 3.0.0
info:
  title: Data Retrieval
  version: '1.0'
  contact:
    name: Support
    url: 'https://forescout.com'
    email: support@forescout.com
servers:
  - url: 'http://localhost:3000'
paths:
  /api/hostfields:
    get:
      summary: Get host fields
      tags:
        - Data
      responses:
        '200':
          description: OK
          content:
            application/hal+json:
              schema:
                $ref: ../models/hostfields.v1.yaml
      operationId: get-api-hostfields
      security:
        - JWT: []
components:
  schemas: {}
  securitySchemes:
    JWT:
      type: http
      scheme: Basic
